-- Created by Vertabelo (http://vertabelo.com)
-- Modified for HSQLDB with fixed ID columns
-- Last modification date: 2025-08-28 14:46:10.192

-- Kustutame tabelid kui on olemas (arenduse jaoks)
DROP TABLE IF EXISTS mixed_color;
DROP TABLE IF EXISTS color;

-- tables
-- Table: color (muudetud fikseeritud ID-dega)
CREATE TABLE color (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(64) NOT NULL,
    r SMALLINT NOT NULL,
    g SMALLINT NOT NULL,
    b SMALLINT NOT NULL,
    hex VARCHAR(7) NULL,
    CONSTRAINT CHECK_0 CHECK (r BETWEEN 0 AND 255),
    CONSTRAINT CHECK_1 CHECK (g BETWEEN 0 AND 255),
    CONSTRAINT CHECK_2 CHECK (b BETWEEN 0 AND 255),
    CONSTRAINT color_pk PRIMARY KEY (id)
);

-- Table: mixed_color (muudetud IDENTITY toega)
CREATE TABLE mixed_color (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    color1_id INTEGER NOT NULL,
    color2_id INTEGER NOT NULL,
    result_r SMALLINT NOT NULL,
    result_g SMALLINT NOT NULL,
    result_b SMALLINT NOT NULL,
    name VARCHAR(64) NULL,
    hex VARCHAR(7) NULL,
    CONSTRAINT uk_mixed_color_pair UNIQUE (color1_id, color2_id),
    CONSTRAINT ck_distinct_sources CHECK (color1_id <> color2_id),
    CONSTRAINT mixed_color_pk PRIMARY KEY (id)
);

-- foreign keys
-- Reference: fk_mixed_color_source1 (table: mixed_color)
ALTER TABLE mixed_color ADD CONSTRAINT fk_mixed_color_source1
    FOREIGN KEY (color1_id)
    REFERENCES color (id);

-- Reference: fk_mixed_color_source2 (table: mixed_color)
ALTER TABLE mixed_color ADD CONSTRAINT fk_mixed_color_source2
    FOREIGN KEY (color2_id)
    REFERENCES color (id);

-- End of file.